#!/bin/bash

# setup path variables
DOMAIN_DIR='domains'
RESULT_DIR='results'
BASE_DIR=`pwd`

# arg1 - domain
# delete files generated by previous experiments with domain
function clean () {
DOMAIN_PATH=${BASE_DIR}/${DOMAIN_DIR}/$1
RESULT_PATH=${BASE_DIR}/${RESULT_DIR}/$1
cd $DOMAIN_PATH

echo -n "cleaning previous experiments .."
[[ -f "experiments" ]] && rm -f "experiments"
[[ -d "execution" ]] && rm -rf "execution"
[[ -d "$RESULT_PATH" ]] && rm -rf "$RESULT_PATH"
echo "OK"
}

function process_domain () {

clean $1

echo "creating result directory: $RESULT_PATH"
[[ -d "$RESULT_PATH" ]] || mkdir -p $RESULT_PATH

cd $DOMAIN_PATH

echo "Submiting jobs to cluster:"
while read planner;
do
	while read model;
	do
                while read task;
                do
                        qsub -v planner="${planner}",model="${model}",task="${task}",domain="$1" $BASE_DIR/crun_one.sh
                done < prob_list
	done < mod_list
done < pla_list

cd $BASE_DIR
}

# ------------- process domains ---------------

# if no parameters are given the script will process all domains in $DOMAIN_DIR
# otherwise each parameter should name domain selected for processing

if [ $# -gt 0 ]; then
  echo "Processing specified domains:"
  for D in $@;
  do
	  echo "==== Processing $D ====";
  	process_domain $D
  done
else
  echo "No parameter specified - processing all domains."
  for D in `ls $DOMAIN_DIR | grep -v README.md`;
  do
    echo "==== Processing $D ====";
    process_domain $D
  done
fi
