#!/bin/bash

DOMAINS=`ls domains`

# assuming that each <domain>/problems directory contains picat file with problem instances generated by Neng Fa Zhou's pddl2pi.pi script adjusted by Marco De Bortoli
# outer loop: filters out the list of benchmarks
# from the line that contains the string "Benches="
#
# inner loop: use generated lists to extract problem instances

for d in $DOMAINS;
do
  # update list of all problems in domain directory
  if [ -f "domains/${d}/${d}_problems" ]; then
    echo "INFO: file \"domains/${d}/${d}_problems\" already existed - replacing."
    rm domains/${d}/${d}_problems
  else
    echo "INFO: creating file \"domains/${d}/${d}_problems\""
  fi
 
  GENERATED_INSTANCES="domains/${d}/problems/${d}.pi"
  head ${GENERATED_INSTANCES} | grep "Benches=" | sed "s/[^\[]*\[\(.*\)\].*/\1/" | tr "," "\n" > domains/${d}/${d}_problems;

  # extract individual problem instances from big file with all generated instances
  while read b;
  do
    RES="domains/${d}/problems/${b}"
    cat ${GENERATED_INSTANCES} | sed -n "/${b} =/,/pddl(Init,Goal)\./p" > ${RES} 
  done < domains/${d}/${d}_problems
done

